name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Build binaries
      run: |
        mkdir -p bin
        GOOS=linux go build -o ./bin/cr_viewer-linux main.go
        GOOS=darwin go build -o ./bin/cr_viewer-darwin main.go
        GOOS=windows go build -o ./bin/cr_viewer-windows.exe main.go

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
